// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/webhook/v1/webhook.proto

package webhookv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // example: "deposit.confirmed", "payout.processed"
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	AttemptCount  int32                  `protobuf:"varint,6,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_proto_webhook_v1_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WebhookEvent) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *WebhookEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *WebhookEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *WebhookEvent) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WebhookEvent) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *WebhookEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DispatchWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *WebhookEvent          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchWebhookRequest) Reset() {
	*x = DispatchWebhookRequest{}
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchWebhookRequest) ProtoMessage() {}

func (x *DispatchWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchWebhookRequest.ProtoReflect.Descriptor instead.
func (*DispatchWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_webhook_v1_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchWebhookRequest) GetEvent() *WebhookEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *DispatchWebhookRequest) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

type DispatchWebhookResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	HttpStatusCode int32                  `protobuf:"varint,2,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"`
	ResponseBody   string                 `protobuf:"bytes,3,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchWebhookResponse) Reset() {
	*x = DispatchWebhookResponse{}
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchWebhookResponse) ProtoMessage() {}

func (x *DispatchWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchWebhookResponse.ProtoReflect.Descriptor instead.
func (*DispatchWebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_webhook_v1_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *DispatchWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DispatchWebhookResponse) GetHttpStatusCode() int32 {
	if x != nil {
		return x.HttpStatusCode
	}
	return 0
}

func (x *DispatchWebhookResponse) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

type RetryDLQWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDLQWebhookRequest) Reset() {
	*x = RetryDLQWebhookRequest{}
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDLQWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDLQWebhookRequest) ProtoMessage() {}

func (x *RetryDLQWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDLQWebhookRequest.ProtoReflect.Descriptor instead.
func (*RetryDLQWebhookRequest) Descriptor() ([]byte, []int) {
	return file_proto_webhook_v1_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *RetryDLQWebhookRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type RetryDLQWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queued        bool                   `protobuf:"varint,1,opt,name=queued,proto3" json:"queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDLQWebhookResponse) Reset() {
	*x = RetryDLQWebhookResponse{}
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDLQWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDLQWebhookResponse) ProtoMessage() {}

func (x *RetryDLQWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webhook_v1_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDLQWebhookResponse.ProtoReflect.Descriptor instead.
func (*RetryDLQWebhookResponse) Descriptor() ([]byte, []int) {
	return file_proto_webhook_v1_webhook_proto_rawDescGZIP(), []int{4}
}

func (x *RetryDLQWebhookResponse) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

var File_proto_webhook_v1_webhook_proto protoreflect.FileDescriptor

const file_proto_webhook_v1_webhook_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/webhook/v1/webhook.proto\x12\n" +
	"webhook.v1\"\xee\x01\n" +
	"\fWebhookEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vmerchant_id\x18\x02 \x01(\x03R\n" +
	"merchantId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12#\n" +
	"\rattempt_count\x18\x06 \x01(\x05R\fattemptCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"g\n" +
	"\x16DispatchWebhookRequest\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.webhook.v1.WebhookEventR\x05event\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\"\x82\x01\n" +
	"\x17DispatchWebhookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x10http_status_code\x18\x02 \x01(\x05R\x0ehttpStatusCode\x12#\n" +
	"\rresponse_body\x18\x03 \x01(\tR\fresponseBody\"3\n" +
	"\x16RetryDLQWebhookRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"1\n" +
	"\x17RetryDLQWebhookResponse\x12\x16\n" +
	"\x06queued\x18\x01 \x01(\bR\x06queued2\xc8\x01\n" +
	"\x0eWebhookService\x12Z\n" +
	"\x0fDispatchWebhook\x12\".webhook.v1.DispatchWebhookRequest\x1a#.webhook.v1.DispatchWebhookResponse\x12Z\n" +
	"\x0fRetryDLQWebhook\x12\".webhook.v1.RetryDLQWebhookRequest\x1a#.webhook.v1.RetryDLQWebhookResponseB.Z,paynexus/pkg/genproto/webhook/v1;webhookv1pbb\x06proto3"

var (
	file_proto_webhook_v1_webhook_proto_rawDescOnce sync.Once
	file_proto_webhook_v1_webhook_proto_rawDescData []byte
)

func file_proto_webhook_v1_webhook_proto_rawDescGZIP() []byte {
	file_proto_webhook_v1_webhook_proto_rawDescOnce.Do(func() {
		file_proto_webhook_v1_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_webhook_v1_webhook_proto_rawDesc), len(file_proto_webhook_v1_webhook_proto_rawDesc)))
	})
	return file_proto_webhook_v1_webhook_proto_rawDescData
}

var file_proto_webhook_v1_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_webhook_v1_webhook_proto_goTypes = []any{
	(*WebhookEvent)(nil),            // 0: webhook.v1.WebhookEvent
	(*DispatchWebhookRequest)(nil),  // 1: webhook.v1.DispatchWebhookRequest
	(*DispatchWebhookResponse)(nil), // 2: webhook.v1.DispatchWebhookResponse
	(*RetryDLQWebhookRequest)(nil),  // 3: webhook.v1.RetryDLQWebhookRequest
	(*RetryDLQWebhookResponse)(nil), // 4: webhook.v1.RetryDLQWebhookResponse
}
var file_proto_webhook_v1_webhook_proto_depIdxs = []int32{
	0, // 0: webhook.v1.DispatchWebhookRequest.event:type_name -> webhook.v1.WebhookEvent
	1, // 1: webhook.v1.WebhookService.DispatchWebhook:input_type -> webhook.v1.DispatchWebhookRequest
	3, // 2: webhook.v1.WebhookService.RetryDLQWebhook:input_type -> webhook.v1.RetryDLQWebhookRequest
	2, // 3: webhook.v1.WebhookService.DispatchWebhook:output_type -> webhook.v1.DispatchWebhookResponse
	4, // 4: webhook.v1.WebhookService.RetryDLQWebhook:output_type -> webhook.v1.RetryDLQWebhookResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_webhook_v1_webhook_proto_init() }
func file_proto_webhook_v1_webhook_proto_init() {
	if File_proto_webhook_v1_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_webhook_v1_webhook_proto_rawDesc), len(file_proto_webhook_v1_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_webhook_v1_webhook_proto_goTypes,
		DependencyIndexes: file_proto_webhook_v1_webhook_proto_depIdxs,
		MessageInfos:      file_proto_webhook_v1_webhook_proto_msgTypes,
	}.Build()
	File_proto_webhook_v1_webhook_proto = out.File
	file_proto_webhook_v1_webhook_proto_goTypes = nil
	file_proto_webhook_v1_webhook_proto_depIdxs = nil
}
